# Generated by Django 5.0.7 on 2024-07-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appeal_app_datetime_alter_appeal_app_name_and_more'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.district'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.region'),
        ),
    ]
