# Generated by Django 5.0.7 on 2024-07-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appeal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='done',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
